apiVersion: v1
kind: Pod
metadata:
  name: alpine2
spec:
  containers:
    - name: alpine2
      image: alpine
      command: ['/bin/ash', '-c', 'trap: TERM INIT; sleep infinity & wait']
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
     