apiVersion: 'k8s.cni.cncf.io/v1'
kind: NetworkAttachmentDefinition
metadata:
  name: calico
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "calico",
    "log_level": "info",
    "datastore_type": "kubernetes",
    "mtu": 1410,
    "nodename_file_optional": false,
    "ipam": {
      "type": "calico-ipam",
      "assign_ipv4": "true",
      "assign_ipv6": "false",
      "ranges": [
        {
          "subnet": "192.168.51.0/24",
          "rangeStart": "192.168.51.100",
          "rangeEnd": "192.168.51.250"
        }
      ]
    },
    "policy": {
      "type": "k8s"
    },
    "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }
  }'
