apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "bond0",
      "mode": "passthru",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.11.0/24",
        "rangeStart": "192.168.11.10",
        "rangeEnd": "192.168.11.254",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
