apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cilium
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "cilium",
    "plugins": [
      {
        "type": "cilium-cni"
      },
      {
        "type": "portmap",
        "capabilities": {"portMappings": true}
      }
    ]
  }'
